UmberFirm\Bundle\CategoryBundle\Entity\CategorySeoTranslation:
    properties:
        title:
            - Length:
                max: 155
        keywords:
            - Length:
                max: 155
