UmberFirm\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        order:
            - NotBlank: ~
        productVariant:
            - NotBlank: ~
        amount:
            - NotBlank: ~
        quantity:
            - NotBlank: ~
        price:
            - NotBlank: ~
