UmberFirm\Bundle\OrderBundle\Entity\ShoppingCart:
    properties:
        quantity:
            - NotBlank: ~
        amount:
            - NotNull: ~
            - Type:
                type: numeric
        shop:
            - NotNull: ~
