UmberFirm\Bundle\OrderBundle\Entity\ShoppingCartItem:
    properties:
        shoppingCart:
            - NotNull: ~
        productVariant:
            - NotNull: ~
        amount:
            - NotBlank: ~
        quantity:
            - NotNull: ~
        price:
            - NotBlank: ~
