UmberFirm\Bundle\OrderBundle\Entity\ShippingAddress:
    properties:
        email:
            - NotBlank: ~
        phone:
            - NotBlank: ~
        fullname:
            - NotBlank: ~
        city:
            - NotBlank: ~
        country:
            - NotBlank: ~
