UmberFirm\Bundle\ProductBundle\Entity\AttributeGroup:
    properties:
        translations:
            - Valid: ~
        attributeGroupEnum:
            - NotNull: ~
        code:
            - NotNull: ~
