UmberFirm\Bundle\CommonBundle\Entity\Language:
    properties:
        code:
            - NotBlank: ~
            - NotNull: ~
            - Length: { min: 2, max: 2 }
        name:
            - NotBlank: ~
            - NotNull: ~
            - Length: { min: 1, max: 150 }
