<?php

declare(strict_types=1);

namespace UmberFirm\Bundle\SupplierBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UmberFirm\Bundle\SupplierBundle\Entity\Supplier;
use UmberFirm\Bundle\SupplierBundle\Entity\SupplierFeatureMapping;

/**
 * SupplierFeatureMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierFeatureMappingRepository extends EntityRepository
{
    /**
     * @param Supplier $supplier
     * @param string $supplierFeatureKey
     * @param string $supplierFeatureValue
     *
     * @return null|object|SupplierFeatureMapping
     */
    public function findOneBySupplierFeature(
        Supplier $supplier,
        string $supplierFeatureKey,
        string $supplierFeatureValue
    ): ?SupplierFeatureMapping {
        return $this->findOneBy(
            [
                'supplier' => $supplier->getId()->toString(),
                'supplierFeatureKey' => $supplierFeatureKey,
                'supplierFeatureValue' => $supplierFeatureValue,
            ]
        );
    }
}
