UmberFirm\Bundle\CustomerBundle\DataObject\CustomerPassword:
    properties:
        oldPassword:
            - UmberFirm\Component\Validator\Constraints\CustomerPassword\CustomerPassword: ~
        password:
            - NotBlank: ~